### PR TITLE
Added the capability to write non-standard 0-based for first frame

### PR DESCRIPTION
**Pull request by pariterre**
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/279)

### CODE REVIEW

**Comment by Svito-zar** [comment]
@pariterre, into which version has this been merged? 
I am not able to access it from python using ezc3d = 1.5.1

**Comment by pariterre** [comment]
@Svito-zar 
That's right! I forgot to update the python interface! I am pushing this today... sorry for that silly mistake

**Comment by Svito-zar** [comment]
Thank you for such a prompt reaction, @pariterre!
I am glad I reach out here instead of just waiting :)

**Comment by pariterre** [comment]
haha indeed! 
#285 should resolve your concerns!

**Comment by Svito-zar** [comment]
yes, it does. works for me now :) thanks a bunch!

**Pull request merged**
