### PR TITLE
Check condition for writing c3d file

### PR DESCRIPTION
**Pull request by beebuzz002**
Hello,

In the __init__.py, line 482 to 485, the check condition is 
if (
                    nb_analog_frames
                    != self._storage["parameters"]["ANALOG"]["RATE"]["value"][0]
                    / self._storage["parameters"]["POINT"]["RATE"]["value"][0]
                    * nb_point_frames
    )

This sometimes raises error when fractions are involved. 
The are some suggestion to fix this thus far, however, I feel that a smoother alternative could be
if (
                    nb_analog_frames * self._storage["parameters"]["POINT"]["RATE"]["value"][0]
                    != nb_point_frames * self._storage["parameters"]["ANALOG"]["RATE"]["value"][0]
                )
This will be able to perform the check without any errors caused and would not rely on other functions to smooth the value out.

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/276)

### CODE REVIEW

**Review by pariterre — APPROVED** [review]
Looks good to me! Thanks for this suggestion :)

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/276#-:-NJegGWJ1MPopB6SgvVK:b-njfn4j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @beebuzz002)

**Review by pariterre — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/276#-:-NJeggpN299vVVBUEQH1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @beebuzz002)

**Comment by beebuzz002** [comment]
Hello,
I think I made the above pull request wrongly. It was not from a forked branch. Is it possible to help to change the code in the stable branch?

**Comment by pariterre** [comment]
Ah! That explains a lot! 
You should use the `dev` branch as the target :P

**Comment by beebuzz002** [comment]
Sure!

**Pull request merged**
