### PR TITLE
CMake improvements

### PR DESCRIPTION
**Pull request by SpaceIm**
- do not force C++11, instead ask to CMake at least C++11 (cxx_std_11 compile feature)
- remove useless enforcement of `CMP0048` to NEW (it's already NEW due to CMake min version ezc3d)
- avoid to force PIC for static lib when octave and matlab bindings are not built
- centralize most CMake options together. It's hard to understand CMake build files logic when options are scattered.
- install:
  - rely on `GNUInstallDirs` and install binaries of ezc3d in standard locations.
  - add version file along CMake config file.
  - also export target file in build tree
  - cleanup config file

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/243)

### CODE REVIEW

**Comment by pariterre** [comment]
Don't have much to say! 
I was always wondering which of include "ezc3d.h" or "ezc3d/ezc3d.h" was the best

Ping me when you feel it is ready to merge :)

**Comment by SpaceIm** [comment]
@pariterre Since there are public headers with very generic names in ezc3d, it's better to put all public headers under this ezc3d folder. Yet, I've kept the possibility to include these headers without `ezc3d/`, to avoid breaking change.

And yes I believe this PR is ready ;)

Oh, maybe I could update README (https://github.com/pyomeca/ezc3d#force-platform-filter) to suggest `#include <ezc3d/ezc3d_all.h>`

**Review by pariterre — APPROVED** [review]
I'll do it :)
Thanks for the PR!

> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 40 of 40 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/243#-:-N2GtH_r60d-9chZmd4Y:b-563q2e)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SpaceIm)

**Review by pariterre — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/243#-:-N2GtLbT9CZaETNujxTL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SpaceIm)

**Pull request merged**
