### PR TITLE
Fix for #264

### PR DESCRIPTION
**Pull request by felixchenier**
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/265)

### CODE REVIEW

**Comment by felixchenier** [comment]
Wait, this comparison works but is too permissive due to the full rounding. I'll submit another, better PR.

**Comment by felixchenier** [comment]
Hi @pariterre 
I modified this PR to put a proper almost-equal float comparison in c3d.write(). I think this would ready to merge, but I didn't run the test suite since I don't have the dev setup configured for building. I can only tell that the same modification applied to my stock ezc3d installation (conda, 1.5.0) works.

**Review by pariterre — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/ezc3d/265)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @felixchenier)

**Review by pariterre — APPROVED** [review]

**Comment by pariterre** [comment]
> Hi @pariterre I modified this PR to put a proper almost-equal float comparison in c3d.write(). I think this would ready to merge, but I didn't run the test suite since I don't have the dev setup configured for building. I can only tell that the same modification applied to my stock ezc3d installation (conda, 1.5.0) works.

No worries, AppVeyor runs the tests from github and they pass! Thanks for the PR :)

**Pull request merged**
